### ADD TEST CONFIRM-DOCUMENTTS
POST http://localhost:8010/test/confirm-documents?iter=1000

### SEARCH
GET http://localhost:8010/api/confirm-documents?requesterId=U00001&confirmDocumentId=&approvalId=&createDate=&confirmStatus=

### ADD APPROVAL

POST http://localhost:8010/api/confirm-documents/607/approvals
Content-Type: application/json

[

  {
    "approvalId": "J20020001",
    "approvalOrder": "1"
  },
  {
    "approvalId": "J19930001",
    "approvalOrder": "2"
  }
]

### 결재 수락
PATCH http://localhost:8010/api/confirm-documents/607/accept
Content-Type: application/json

{
   "companyId": "",
   "departmentId": "",
   "approvalLineId": "J19930001"
}

### 결재 반려
PATCH http://localhost:8010/api/confirm-documents/607/reject
Content-Type: application/json

{
  "companyId": "",
  "departmentId": "",
  "approvalLineId": "J20020001"
}