### 결재 문서 양식 메타 정보 생성 1
POST http://localhost:8000/admin/confirm-document-forms
Content-Type: application/json

{
  "formId": "COST",
  "formName": "경비 사용 내역서",
  "companyId": "SPY"
}

### 결재 문서 요소 생성
POST http://localhost:8000/admin/confirm-document-forms/cost/elements
Content-Type: application/json

{
  "companyId": "com",
  "elementGroupKey": "BAISC_REQUEST_INFO",
  "elementGroupName": "요청 정보",
  "elementGroupType":"PAIR",
  "elementGroupOrder": 1,
  "elementPairs": [
    {
      "elementKey": "card_user",
      "elementName": "카드 사용자",
      "elementOrder": 1
    },
    {
      "elementKey": "use_duration",
      "elementName": "사용기간",
      "elementOrder": 2
    }
  ]
}

### 결재 문서 요소 생성
POST http://localhost:8000/admin/confirm-document-forms/cost/elements
Content-Type: application/json

{
  "companyId": "com",
  "elementGroupKey": "USAGE_HISTORY",
  "elementGroupName": "사용 내역",
  "elementGroupType":"TABLE",
  "elementGroupOrder": 2,
  "elementPairs": [
    {
      "elementKey": "use_datetime",
      "elementName": "사용시간",
      "elementOrder": 1
    },
    {
      "elementKey": "user",
      "elementName": "사용자",
      "elementOrder": 2
    },
    {
      "elementKey": "use_type",
      "elementName": "구분",
      "elementOrder": 3
    },
    {
      "elementKey": "use_detail",
      "elementName": "사용내역(상세 기재)",
      "elementOrder": 4
    },
    {
      "elementKey": "usage_cost",
      "elementName": "사용금액",
      "elementOrder": 5
    },
    {
      "elementKey": "note",
      "elementName": "비고",
      "elementOrder": 6
    }
  ]
}

###
GET http://localhost:8000/api/v2/confirm-document-forms/cost/elements?companyId=com,spy