### 결재 문서 생성
POST http://localhost:8000/api/confirm-documents
Content-Type: application/json

{
  "companyId" : "SPY",
  "departmentId" : "SPY00204",
  "departmentName" : "응급의료정보화팀",
  "createSystem" : "CONFIRM",
  "documentType" : "DCR",
  "requesterId": "SPY00050",
  "requesterName" : "박지현"
}