### 결재 문서 생성 1
POST http://localhost:8000/api/confirm-documents
Content-Type: application/json

{
  "companyId" : "SPY",
  "departmentId" : "SPY00204",
  "departmentName" : "응급의료정보화팀",
  "createSystem" : "CONFIRM",
  "documentType" : "DCR",
  "requesterId": "SPY00050",
  "requesterName" : "박지현"
}

### 결재 문서 생성 2
POST http://localhost:8000/api/confirm-documents
Content-Type: application/json

{
  "companyId" : "SPY",
  "departmentId" : "SPY00204",
  "departmentName" : "응급의료정보화팀",
  "createSystem" : "CONFIRM",
  "documentType" : "DCR",
  "requesterId": "SPY00030",
  "requesterName" : "이종석"
}

###
GET http://localhost:8000/api/confirm-documents/search?startDate=2024-06-01&endDate=2024-07-23&page=1&size=2